# This file was generated by GoReleaser. DO NOT EDIT.
cask "tenet" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "2cff84bb6bf16bc54d5483b3bb7788deef902897e1f608570abd0f1a52a72696"
      url "https://github.com/zoidsh/tenet/releases/download/v#{version}/tenet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "692dfd9ced7b08ef6e07d90f20fc2bd3595621afe98fa15b0ace9fa4dfb526e5"
      url "https://github.com/zoidsh/tenet/releases/download/v#{version}/tenet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f97373a8f3bfbc8819ff1bd1543bc6c777c6cef20c8caa0e80e9476a533e3c1a"
      url "https://github.com/zoidsh/tenet/releases/download/v#{version}/tenet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "18fd3ff35704db0645f93d2e540087ca4e6a8d05db8dc38b10d7d0a695732717"
      url "https://github.com/zoidsh/tenet/releases/download/v#{version}/tenet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tenet"
  desc "The review gate for code that agents write: rules in plain language, judged on every commit"
  homepage "https://github.com/zoidsh/tenet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tenet"

  postflight do
    if File.executable?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required
end
