# This file was generated by GoReleaser. DO NOT EDIT.
cask "tenet" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "d7d339f21dcc68f6bec047283b5fb1bcfa455d1eef687a232a1f0daceca73b68"
      url "https://github.com/zoidsh/tenet/releases/download/v#{version}/tenet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a0a7b8f703125f35a1e78ad3c4366fae6a2559aaad97c49112246058286d710e"
      url "https://github.com/zoidsh/tenet/releases/download/v#{version}/tenet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d22588f59066a4871ed49a5909bce54128f69db8a8e49fbe07ec088998a94c83"
      url "https://github.com/zoidsh/tenet/releases/download/v#{version}/tenet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4cbcf624ed55783cd91dc01eec60ffae82455a6af505dd90cbec8f7cdcb727d2"
      url "https://github.com/zoidsh/tenet/releases/download/v#{version}/tenet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tenet"
  desc "The review gate for code that agents write: rules in plain language, judged on every commit"
  homepage "https://github.com/zoidsh/tenet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tenet"

  postflight do
    if File.executable?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required
end
