# This file was generated by GoReleaser. DO NOT EDIT.
cask "tenet" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "052c7524509447cefbd076ad4439e9daee172f7b7b9215085604a3fe1b1c3c43"
      url "https://github.com/zoidsh/tenet/releases/download/v#{version}/tenet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "587d9a5cb32de01e53a5ca1b97ad37efcd7b882b911d73f711c75b6269810e10"
      url "https://github.com/zoidsh/tenet/releases/download/v#{version}/tenet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b2aa6b36de0224d15f46edaa75c484b6e653da140e8936447bfb61a274895a09"
      url "https://github.com/zoidsh/tenet/releases/download/v#{version}/tenet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "af9e461ea96ca43c472d8f3b3ea0ac9856b3df649ff2ea6345d31014022446c7"
      url "https://github.com/zoidsh/tenet/releases/download/v#{version}/tenet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tenet"
  desc "The review gate for code that agents write: rules in plain language, judged on every commit"
  homepage "https://github.com/zoidsh/tenet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tenet"

  postflight do
    if File.executable?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required
end
